In [1]:
import sys
sys.path.append('../src/')
from settings import config
from pathlib import Path
OUTPUT_DIR = Path(config("OUTPUT_DIR"))
DATA_DIR = Path(config("DATA_DIR"))
WRDS_USERNAME = config("WRDS_USERNAME")
import pandas as pd
import wrds
import numpy as np

In [2]:
db = wrds.Connection(wrds_username=WRDS_USERNAME)

Loading library list...
Done

In [3]:
db.describe_table(library="tr_ds_fut", table="wrds_contract_info")

Approximately 435664 rows in tr_ds_fut.wrds_contract_info.

,name,nullable,type,comment
0,futcode,True,"NUMERIC(11, 0)",FutCode - Refinitiv ID for a Datastream mnemonic
1,contrcode,True,"NUMERIC(11, 0)",ContrCode - Refinitiv generated ID for a Datas...
2,clscode,True,"NUMERIC(11, 0)",ClsCode - Refinitiv code for a Datastream clas...
3,dsmnem,True,VARCHAR(10),DSMnem - Datastream mnemonic
4,contrname,True,VARCHAR(90),ContrName - Contract Name
5,ldb,True,VARCHAR(3),LDB - Logical database code; Datastream Future...
6,contrdate,True,VARCHAR(12),ContrDate - Contract date in the string format...
7,contrdatefmt,True,VARCHAR(8),ContrDateFmt - (reserved for future development)
8,isocurrcode,True,VARCHAR(3),ISOCurrCode - ISO Currency Code for the curren...
9,isocurrdesc,True,VARCHAR(90),Desc_ - Full name or description of Code + Type_
10,currunitcode,True,VARCHAR(4),CurrUnitCode - Indicates the unit of currency....
11,unitcode,True,"NUMERIC(11, 0)",UnitCode - Indicates the units of a futures co...
12,unitdesc,True,VARCHAR(90),Desc_ - Full name or description of Code + Type_
13,trdstatcode,True,VARCHAR(1),TrdStatCode - Status code and indicates whethe...
14,startdate,True,DATE,StartDate - Indicates the date from which the ...
15,lasttrddate,True,DATE,Date on which the contract expires
16,sttlmntdate,True,DATE,SttlmntDate - The date when the contract is se...
17,expirationdate,True,DATE,ExpirationDate - (reserved for future developm...
18,firstnoticedate,True,DATE,FirstNoticeDate - The day after which an inves...
19,lastnoticedate,True,DATE,LastNoticeDate - (reserved for future developm...
20,firstdelvrydate,True,DATE,FirstDelvryDate - (reserved for future develop...
21,ticksizeunitcode,True,"NUMERIC(11, 0)",TickSizeUnitCode - (reserved for future develo...
22,exchtickersymb,True,VARCHAR(12),ExchTickerSymb - Security ticker or symbol pro...
23,trdmonths,True,VARCHAR(30),Trading Cycle Months

In [230]:
query = """SELECT * FROM tr_ds_fut.wrds_contract_info
        WHERE contrname ILIKE '%%copper%%'
        ORDER BY startdate ASC
        LIMIT 1000"""
        #WHERE exchtickersymb ILIKE '%%PN%%'
        #WHERE contrname ILIKE '%%Propane%%'
        #AND contrdate = '0110'
        #AND ldb = 'COM'
        
        

data = db.raw_sql(query)
#display(data['contrname'])
#data['contrname'].unique()
data.drop_duplicates(subset='contrname', keep='first')

,futcode,contrcode,clscode,dsmnem,contrname,ldb,contrdate,contrdatefmt,isocurrcode,isocurrdesc,...,startdate,lasttrddate,sttlmntdate,expirationdate,firstnoticedate,lastnoticedate,firstdelvrydate,ticksizeunitcode,exchtickersymb,trdmonths
0,322868.0,2026.0,1512.0,NHG0789,COPPER (HIGH GRADE),COM,0789,None,USD,US Dollar,...,1988-07-29,1989-07-27,1989-08-01,None,None,None,None,None,HG,ALL
70,76605.0,3123.0,2328.0,SCU1193,COPPER,CIE,1193,None,CNY,Yuan Renminbi,...,1993-05-26,1993-11-15,1993-11-16,None,None,None,None,None,cu,ALL
373,183578.0,1519.0,1135.0,LFC1010,LMEMINI COPPER,CIE,1010,None,USD,US Dollar,...,2000-10-26,2010-10-18,2010-10-18,None,None,None,None,None,MCD,ALL
685,316250.0,2083.0,1557.0,NQC0107,COPPER MINY,COM,0107,None,USD,US Dollar,...,2006-12-04,2006-12-27,2006-12-27,None,None,None,None,None,QC,ALL

In [93]:
query = """SELECT * FROM tr_ds_fut.wrds_contract_info
        WHERE contrcode = 3847
        LIMIT 1000"""

data = db.raw_sql(query)
pd.set_option('display.max_colwidth', None)
#display(data['contrname'])
#data

In [3]:
db.describe_table(library="tr_ds_fut", table="wrds_fut_contract")

Approximately 162566319 rows in tr_ds_fut.wrds_fut_contract.

,name,nullable,type,comment
0,futcode,True,"NUMERIC(11, 0)",FutCode - Refinitiv ID for a Datastream mnemonic
1,date_,True,DATE,Date_ - Market date
2,open_,True,DOUBLE PRECISION,Open_ - Opening value of a contract. This valu...
3,high,True,DOUBLE PRECISION,High - High value of a contract trade. If ther...
4,low,True,DOUBLE PRECISION,Low - Low value of a contract trade. If there ...
5,volume,True,DOUBLE PRECISION,Volume - Trade volume for the given date
6,settlement,True,DOUBLE PRECISION,Settlement - Settlement price as published and...
7,openinterest,True,DOUBLE PRECISION,OpenInterest - Total number of contracts enter...
8,p,True,DOUBLE PRECISION,Price - Closing
9,pb,True,DOUBLE PRECISION,Price Bid
10,pa,True,DOUBLE PRECISION,Price Ask
11,wa,True,DOUBLE PRECISION,Weighted Average price
12,ca,True,DOUBLE PRECISION,Price - Close APT
13,yd,True,DOUBLE PRECISION,Yield
14,hm,True,DOUBLE PRECISION,Price - High AM Session
15,ha,True,DOUBLE PRECISION,Price - High PM Session
16,mt,True,DOUBLE PRECISION,Price - Last traded AM Session
17,la,True,DOUBLE PRECISION,Price - Low AM Session
18,lm,True,DOUBLE PRECISION,Price - Low PM Session
19,oa,True,DOUBLE PRECISION,Price - Opening PM Session
20,up,True,DOUBLE PRECISION,Unadjusted Price

In [94]:
query = """SELECT * FROM tr_ds_fut.wrds_fut_contract WHERE futcode = 629 LIMIT 10000"""
data = db.raw_sql(query)
#data

# cgpt attempt:

Propane = Mont Belvieu LDH Propane (OPIS) Swap Pit = 3847; ONLY POST 2009, NO PROPANE FUTURES FOUND BEFORE THEN

Broilers = No contracts exist at all. ChatGPT doesn't even know of any chicken/poultry/broiler futures that would be trading pre 2008.

In [231]:
summary_table = pd.DataFrame(columns=[
    "Commodity",
    "Contract Code",
    "N", 
    "Basis", 
    "Freq. of Backwardation (%)", 
    "E(Re) (Mean Annual Excess Return)", 
    "σ(Re) (Std Dev of Excess Return)", 
    "Sharpe Ratio"
])

In [232]:
for product_contract_code in [3160, 289, 3161, 1980, 2038, 3247, 1992, 361, 385, 2036, 379, 3256, 396, 430,
                              1986, 2091, 2029, 2060, 3847, 2032,
                              3250, 2676, 2675,
                              3126, 2087, 2026, 2020, 2065, 2074, 2108]:
    # Step 1: Get relevant futcodes for product
    query_info = f"""
    SELECT futcode, contrcode, contrname, startdate, lasttrddate
    FROM tr_ds_fut.wrds_contract_info
    WHERE contrcode = {product_contract_code}
    AND startdate >= '1970-01-01' AND lasttrddate <= '2008-12-31'
    """
    data_info = db.raw_sql(query_info)
    if len(data_info) == 0:
        print("No data available for the specified product. Product Code:", product_contract_code)
        continue

    
    # Extract relevant futcodes
    ng_futcodes = tuple(data_info["futcode"].unique())

    # Step 2: Get settlement prices for NG contracts
    query_contracts = f"""
    SELECT futcode, date_, settlement
    FROM tr_ds_fut.wrds_fut_contract
    WHERE futcode IN {ng_futcodes}
    AND date_ >= '1970-01-01' AND date_ <= '2008-12-31'
    """
    data_contracts = db.raw_sql(query_contracts)

    # Convert date column to datetime
    data_contracts["date_"] = pd.to_datetime(data_contracts["date_"])

    # Extract year-month for grouping
    data_contracts["month"] = data_contracts["date_"].dt.to_period("M")

    # Step 3: Get prompt & 12-month futures settlement prices
    def get_prompt_and_12m(group):
        """Extract nearest and 12-month maturity contract settlement prices for each month."""
        group = group.sort_values(by="date_")
        prompt_contract = group.iloc[0]  # First contract (nearest)
        contract_12m = group.iloc[-1] if len(group) > 1 else None  # Last contract (12 months out)
        
        return pd.Series({
            "prompt_settlement": prompt_contract["settlement"],
            "contract_12m_settlement": contract_12m["settlement"] if contract_12m is not None else None
        })

    # Apply function to get prompt & 12-month contracts per month
    monthly_contracts = data_contracts.groupby("month").apply(get_prompt_and_12m, include_groups=False).reset_index()

    # Step 4: Compute the basis
    monthly_contracts["basis"] = np.log(monthly_contracts["prompt_settlement"]) - np.log(monthly_contracts["contract_12m_settlement"])
    monthly_contracts["basis"] /= 11  # Annualized basis

    # Step 5: Compute frequency of backwardation
    freq_backwardation = (monthly_contracts["basis"] > 0).mean() * 100

    # Compute excess return for the prompt contract
    monthly_contracts["excess_return"] = monthly_contracts["prompt_settlement"].pct_change() * 100

    # Compute mean and std deviation of annualized excess return
    excess_return_mean = monthly_contracts["excess_return"].mean()
    excess_return_std = monthly_contracts["excess_return"].std()

    # Compute Sharpe Ratio
    sharpe_ratio = excess_return_mean / excess_return_std if excess_return_std != 0 else np.nan

    # Count number of valid observations
    N = len(monthly_contracts.dropna())

    summary_table = pd.concat([summary_table, pd.DataFrame({
        "Commodity": [data_info['contrname'].unique()[0]],
        "Contract Code": [data_info['contrcode'].unique()[0]],
        "N": [N],
        "Basis": [monthly_contracts["basis"].mean()],
        "Freq. of Backwardation (%)": [freq_backwardation],
        "E(Re) (Mean Annual Excess Return)": [excess_return_mean],
        "σ(Re) (Std Dev of Excess Return)": [excess_return_std],
        "Sharpe Ratio": [sharpe_ratio]
    })], ignore_index=True)

/var/folders/h0/qptzh67n0md7rt72m1nzqjtw0000gn/T/ipykernel_70954/174479892.py:71: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  summary_table = pd.concat([summary_table, pd.DataFrame({

No data available for the specified product. Product Code: 3847

/var/folders/h0/qptzh67n0md7rt72m1nzqjtw0000gn/T/ipykernel_70954/174479892.py:59: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  monthly_contracts["excess_return"] = monthly_contracts["prompt_settlement"].pct_change() * 100
/var/folders/h0/qptzh67n0md7rt72m1nzqjtw0000gn/T/ipykernel_70954/174479892.py:59: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  monthly_contracts["excess_return"] = monthly_contracts["prompt_settlement"].pct_change() * 100
/var/folders/h0/qptzh67n0md7rt72m1nzqjtw0000gn/T/ipykernel_70954/174479892.py:59: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  monthly_contracts["excess_return"] = monthly_contracts["prompt_settlement"].pct_change() * 100

In [233]:
summary_table

,Commodity,Contract Code,N,Basis,Freq. of Backwardation (%),E(Re) (Mean Annual Excess Return),σ(Re) (Std Dev of Excess Return),Sharpe Ratio
0,WESTERN BARLEY,3160.0,308,-0.001552,42.718447,0.375292,7.340499,0.051126
1,BUTTER (CASH),289.0,39,-0.000425,37.500000,-0.077732,4.777912,-0.016269
2,CANOLA,3161.0,346,-0.001146,40.057637,0.272432,6.320588,0.043102
3,COCOA,1980.0,424,0.000314,49.411765,0.496263,8.775294,0.056552
4,COFFEE 'C',2038.0,373,0.000526,52.941176,0.490991,10.555662,0.046514
5,CORN,3247.0,431,-0.000512,41.898148,0.409978,6.800101,0.060290
6,COTTON #2,1992.0,374,-0.000248,47.200000,0.135108,6.233259,0.021675
7,LUMBER,361.0,369,-0.001204,41.891892,0.292220,7.716107,0.037871
8,OATS,385.0,368,-0.000347,46.883469,0.518984,10.057856,0.051600
9,ORANGE JUICE (FCOJ-A),2036.0,423,-0.001733,41.981132,0.489120,9.379203,0.052149
10,RICE (ROUGH),379.0,267,0.001361,55.597015,0.908364,9.583024,0.094789
11,SOYBEAN MEAL,3256.0,424,0.001207,56.941176,0.335065,8.128210,0.041222
12,SOYBEANS,396.0,369,0.000476,51.351351,0.360765,6.853292,0.052641
13,WHEAT,430.0,371,0.001049,55.645161,0.356906,6.653742,0.053640
14,CRUDE OIL (LIGHT SWEET),1986.0,309,0.001208,56.774194,0.439366,7.273284,0.060408
15,GASOLINE RBOB,2091.0,38,-0.004231,33.333333,-0.343296,12.244473,-0.028037
16,HEATING OIL (NEW YORK),2029.0,361,-0.000698,48.066298,0.688514,8.221374,0.083747
17,NATURAL GAS,2060.0,224,-0.001265,42.666667,0.957275,9.167379,0.104422
18,GASOLINE UNLEADED (NEW YORK),2032.0,263,0.000354,50.943396,0.662332,8.449752,0.078385
19,FEEDER CATTLE COMP.,3250.0,364,0.000479,52.602740,0.183284,3.778843,0.048503
20,LEAN HOGS COMP.,2676.0,389,0.000908,55.641026,0.397055,7.969933,0.049819
21,LIVE CATTLE COMP.,2675.0,359,-0.001534,37.500000,0.151419,3.618213,0.041849
22,ALUMINIUM,3126.0,181,-0.000094,51.098901,0.129451,4.458307,0.029036
23,COAL,2087.0,88,0.000281,51.111111,0.929010,8.860725,0.104846
24,COPPER (HIGH GRADE),2026.0,245,-0.000264,52.439024,0.532145,7.351366,0.072387
25,GOLD (100 OZ),2020.0,376,-0.000302,47.214854,0.680769,7.365955,0.092421
26,PALLADIUM,2065.0,370,-0.000216,47.860963,0.857232,10.562973,0.081154
27,PLATINUM,2074.0,416,0.000413,50.359712,0.722730,8.222960,0.087892
28,SILVER (5000 OZ),2108.0,431,0.000285,52.777778,0.829839,9.846766,0.084275

In [234]:
table_1_actual_N ={
    "3160.0": 235,  # Barley
    "289.0": 141,   # Butter
    "3161.0": 377,  # Canola
    "1980.0": 452,  # Cocoa
    "2038.0": 420,  # Coffee
    "3247.0": 468,  # Corn
    "1992.0": 452,  # Cotton
    "361.0": 468,   # Lumber
    "385.0": 468,   # Oats
    "2036.0": 448,  # Orange Juice
    "379.0": 265,  # Rough Rice
    "3256.0": 468,  # Soybean Meal
    "396.0": 468,   # Soybeans
    "430.0": 468,   # Wheat
    "1986.0": 295,  # Crude Oil
    "2091.0": 275,  # Gasoline
    "2029.0": 345,  # Heating Oil
    "2060.0": 216,  # Natural Gas
    #"3847": 247,        # Propane (No match found in left table)
    "2032.0": 250,    # Unleaded Gas
    #"": 19,         # Broilers (No match found in left table)
    "3250.0": 443,  # Feeder Cattle
    "2676.0": 468,  # Lean Hogs
    "2675.0": 468,  # Live Cattle
    "3126.0": 215,  # Aluminium
    "2087.0": 85,   # Coal
    "2026.0": 412,  # Copper
    "2020.0": 400,  # Gold
    "2065.0": 362,  # Palladium
    "2074.0": 410,  # Platinum
    "2108.0": 419   # Silver
}

In [235]:
summary_table["Actual N"] = summary_table["Contract Code"].astype(str).map(table_1_actual_N)
summary_table = summary_table[['Commodity', 'Contract Code', 'N', 'Actual N', 'Basis', 'Freq. of Backwardation (%)', 'E(Re) (Mean Annual Excess Return)', 'σ(Re) (Std Dev of Excess Return)', 'Sharpe Ratio']]

In [236]:
summary_table_comparison = summary_table[['Commodity', 'Contract Code', 'N', 'Actual N']]
summary_table_comparison["N_diff"] = summary_table_comparison["N"] - summary_table_comparison["Actual N"]
summary_table_comparison['N_diff_pct'] = summary_table_comparison['N_diff'] / summary_table_comparison['Actual N'] * 100

/var/folders/h0/qptzh67n0md7rt72m1nzqjtw0000gn/T/ipykernel_70954/2623030268.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  summary_table_comparison["N_diff"] = summary_table_comparison["N"] - summary_table_comparison["Actual N"]
/var/folders/h0/qptzh67n0md7rt72m1nzqjtw0000gn/T/ipykernel_70954/2623030268.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  summary_table_comparison['N_diff_pct'] = summary_table_comparison['N_diff'] / summary_table_comparison['Actual N'] * 100

In [237]:
summary_table_comparison

,Commodity,Contract Code,N,Actual N,N_diff,N_diff_pct
0,WESTERN BARLEY,3160.0,308,235,73,31.06383
1,BUTTER (CASH),289.0,39,141,-102,-72.340426
2,CANOLA,3161.0,346,377,-31,-8.222812
3,COCOA,1980.0,424,452,-28,-6.19469
4,COFFEE 'C',2038.0,373,420,-47,-11.190476
5,CORN,3247.0,431,468,-37,-7.905983
6,COTTON #2,1992.0,374,452,-78,-17.256637
7,LUMBER,361.0,369,468,-99,-21.153846
8,OATS,385.0,368,468,-100,-21.367521
9,ORANGE JUICE (FCOJ-A),2036.0,423,448,-25,-5.580357
10,RICE (ROUGH),379.0,267,265,2,0.754717
11,SOYBEAN MEAL,3256.0,424,468,-44,-9.401709
12,SOYBEANS,396.0,369,468,-99,-21.153846
13,WHEAT,430.0,371,468,-97,-20.726496
14,CRUDE OIL (LIGHT SWEET),1986.0,309,295,14,4.745763
15,GASOLINE RBOB,2091.0,38,275,-237,-86.181818
16,HEATING OIL (NEW YORK),2029.0,361,345,16,4.637681
17,NATURAL GAS,2060.0,224,216,8,3.703704
18,GASOLINE UNLEADED (NEW YORK),2032.0,263,250,13,5.2
19,FEEDER CATTLE COMP.,3250.0,364,443,-79,-17.832957
20,LEAN HOGS COMP.,2676.0,389,468,-79,-16.880342
21,LIVE CATTLE COMP.,2675.0,359,468,-109,-23.290598
22,ALUMINIUM,3126.0,181,215,-34,-15.813953
23,COAL,2087.0,88,85,3,3.529412
24,COPPER (HIGH GRADE),2026.0,245,412,-167,-40.533981
25,GOLD (100 OZ),2020.0,376,400,-24,-6.0
26,PALLADIUM,2065.0,370,362,8,2.209945
27,PLATINUM,2074.0,416,410,6,1.463415
28,SILVER (5000 OZ),2108.0,431,419,12,2.863962